# GARCH Predictor Configuration - Precog Mode
# GARCH models for Bitcoin price volatility prediction (precog mode only)

model:
  name: "GARCH"
  prediction_mode: "precog"
  
  # GARCH model parameters
  p: 1  # Order of GARCH terms
  q: 1  # Order of ARCH terms
  model_type: "garch"  # Options: "garch", "egarch"
  
  # Volatility prediction parameters
  volatility_window: 20  # Window for volatility estimation
  forecast_horizon: 12  # Forecast horizon (1 hour)
  confidence_level: 0.95  # Confidence level for intervals
  
  # Ensemble parameters (if using ensemble)
  use_ensemble: false
  ensemble_models: ["garch", "egarch"]
  ensemble_weights: null  # Will be determined automatically

data:
  # Time series parameters
  lookback_window: 72  # 6 hours (5-minute intervals)
  prediction_horizon: 12  # 1 hour (5-minute intervals)
  
  # Feature engineering
  use_technical_indicators: true
  use_temporal_features: true
  use_whale_features: true
  
  # Data preprocessing
  scaling_method: "none"  # GARCH works with raw returns
  handle_outliers: true
  outlier_method: "iqr"
  
  # Data splits
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  
  # Time series split
  time_series_split: true
  cv_folds: 5

training:
  # GARCH-specific training parameters
  optimization_method: "scipy"  # Options: "scipy", "custom"
  max_iterations: 1000
  tolerance: 1e-6
  
  # Model fitting parameters
  fit_method: "mle"  # Maximum likelihood estimation
  initialization: "auto"  # Automatic parameter initialization
  
  # Regularization
  parameter_constraints: true
  stationarity_check: true
  
  # Checkpointing
  save_best_model: true
  save_last_model: true
  checkpoint_every: 10

# Optuna hyperparameter optimization
optuna:
  # Study configuration
  study_name: "garch_precog_optimization"
  direction: "minimize"
  n_trials: 50  # Fewer trials due to computational cost
  timeout: 43200  # 12 hours
  
  # Pruning and sampling
  pruner: "hyperband"
  sampler: "tpe"
  n_startup_trials: 5
  n_warmup_steps: 3
  
  # Hyperparameter search spaces
  search_spaces:
    # GARCH model parameters
    p:
      type: "int"
      low: 1
      high: 3
    
    q:
      type: "int"
      low: 1
      high: 3
    
    model_type:
      type: "categorical"
      choices: ["garch", "egarch"]
    
    # Volatility parameters
    volatility_window:
      type: "int"
      low: 10
      high: 50
      step: 5
    
    forecast_horizon:
      type: "int"
      low: 6
      high: 24
      step: 6
    
    confidence_level:
      type: "float"
      low: 0.90
      high: 0.99
      step: 0.01
    
    # Optimization parameters
    max_iterations:
      type: "int"
      low: 500
      high: 2000
      step: 100
    
    tolerance:
      type: "float"
      low: 1e-8
      high: 1e-4
      log: true

# Loss function configuration
loss:
  # Precog-specific loss components
  point_loss_weight: 0.5
  interval_loss_weight: 0.5
  
  # GARCH-specific losses
  volatility_loss_weight: 0.1
  stationarity_penalty: 0.01
  
  # Regularization losses
  l1_regularization: 0.0
  l2_regularization: 0.0

# Evaluation metrics
metrics:
  # Point prediction metrics
  - "mae"
  - "mse"
  - "rmse"
  - "mape"
  - "smape"
  
  # Interval prediction metrics
  - "interval_coverage"
  - "interval_width"
  - "interval_score"
  
  # GARCH-specific metrics
  - "volatility_accuracy"
  - "stationarity_test"
  - "persistence_measure"
  - "leverage_effect"
  
  # Model fit metrics
  - "aic"
  - "bic"
  - "log_likelihood"
  - "ljung_box_test"

# Model saving and loading
model_save:
  save_dir: "./models/garch_precog"
  save_format: "pickle"  # GARCH models are saved as pickle
  save_parameters: true
  save_fitted_models: true
  versioning: true

# Logging and monitoring
logging:
  level: "INFO"
  log_dir: "./logs/garch_precog"
  tensorboard: false  # GARCH doesn't use tensorboard
  wandb: false
  
  # What to log
  log_model_parameters: true
  log_optimization_progress: true
  log_convergence_info: true
  log_stationarity_tests: true
  
  # Logging frequency
  log_every_n_steps: 10
  validate_every_n_epochs: 1
  
# Hardware and performance
hardware:
  device: "cpu"  # GARCH models run on CPU
  mixed_precision: false
  compile_model: false
  
  # Multi-processing settings
  n_jobs: 4  # Number of parallel jobs for ensemble
  parallel_fitting: true
  
  # Memory optimization
  memory_efficient: true
  chunk_size: 1000  # Process data in chunks
  
# Random seed for reproducibility
seed: 42

# Debugging and development
debug:
  enabled: false
  profile_optimization: false
  check_stationarity: true
  validate_parameters: true 